(setq user-custom-package-list
    '(general
      evil
      evil-collection
      rainbow-delimiters
      ivy
      ivy-rich
      counsel
      helpful
      doom-modeline
      doom-themes
      which-key
      dashboard
      neotree
      treemacs
      perspective
      all-the-icons
      projectile
      counsel-projectile
      vterm
      minimap
      magit
      org
      org-bullets
      visual-fill-colum
      lsp-mode
      lsp-ui
      lsp-treemacs
      lsp-ivy
      flycheck
      yasnippet
      yasnippet-snippets
      company
      company-box
      dired-single
      dired-open
      dired-hide-dotfiles
      all-the-icons-dired
      dap-mode
      beacon
      ranger
      rainbow-mode
      savehist
      vertico))
